version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/nextstep
permissions:
   - object: /var/www/html/nextstep
     pattern: "*"
     owner: www
     group: www
     mode: 755
     type:
      - file
hooks:
  BeforeInstall:
    - location: pre_deploy.sh
  AfterInstall:
    - location: deploy.sh
